"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { todayISO } from "@/lib/checkpoints";
import { DIFFICULTIES } from "@/lib/types";

export default function ProblemForm() {
  const router = useRouter();
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setError(null);
    setSaving(true);

    const form = new FormData(e.currentTarget);

    // The checkpoint ladder is generated by a DB trigger on insert.
    const { data, error } = await createClient()
      .from("questions")
      .insert({
        leetcode_number: Number(form.get("leetcode_number")),
        title: form.get("title"),
        url: form.get("url"),
        difficulty: form.get("difficulty"),
        topic: form.get("topic"),
        confidence: Number(form.get("confidence")),
        date_solved: form.get("date_solved"),
        notes: (form.get("notes") as string) || null,
      })
      .select("id")
      .single();

    if (error) {
      setError(
        error.code === "23505"
          ? "That LeetCode number is already tracked."
          : error.message
      );
      setSaving(false);
      return;
    }

    // Land on the new problem's page so its notes photo can be attached immediately.
    router.push(`/problems/${data.id}`);
    router.refresh();
  }

  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-5">
      <div className="grid grid-cols-2 gap-4">
        <label className="flex flex-col gap-1.5 text-sm text-muted">
          LeetCode number
          <input name="leetcode_number" type="number" min={1} required placeholder="1" className="field data" />
        </label>
        <label className="flex flex-col gap-1.5 text-sm text-muted">
          Date solved
          <input name="date_solved" type="date" defaultValue={todayISO()} required className="field data" />
        </label>
      </div>

      <label className="flex flex-col gap-1.5 text-sm text-muted">
        Title
        <input name="title" required placeholder="Two Sum" className="field" />
      </label>

      <label className="flex flex-col gap-1.5 text-sm text-muted">
        URL
        <input
          name="url"
          type="url"
          required
          placeholder="https://leetcode.com/problems/two-sum/"
          className="field"
        />
      </label>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <label className="flex flex-col gap-1.5 text-sm text-muted">
          Difficulty
          <select name="difficulty" required className="field">
            {DIFFICULTIES.map((d) => (
              <option key={d}>{d}</option>
            ))}
          </select>
        </label>
        <label className="flex flex-col gap-1.5 text-sm text-muted">
          Topic
          <input name="topic" required placeholder="two-pointers" className="field" />
        </label>
        <label className="flex flex-col gap-1.5 text-sm text-muted">
          Confidence
          <select name="confidence" defaultValue="3" required className="field data">
            {[1, 2, 3, 4, 5].map((n) => (
              <option key={n} value={n}>
                {n} / 5
              </option>
            ))}
          </select>
        </label>
      </div>

      <label className="flex flex-col gap-1.5 text-sm text-muted">
        Notes <span className="text-faint">(optional)</span>
        <textarea
          name="notes"
          rows={4}
          placeholder="Key insight, pattern, the thing future-you forgets…"
          className="field resize-y"
        />
      </label>

      {error && <p className="text-sm text-danger">{error}</p>}

      <button type="submit" disabled={saving} className="btn-primary self-start">
        {saving ? "Saving…" : "Add to logbook"}
      </button>
    </form>
  );
}
